apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
type: Opaque
data:
  JwtSettings__Secret: N2NDUkd1T2djZ2VDVWdLM3lUZHhiZTRQSDdhbUZITUQ=  
  MongoSettings__ConnectionString: bW9uZ29kYjovL2FkbWluOlNDM2huJTQwMW1hbmdvJTIxQG1vbmdvZGIuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy9lc3BlcmFuY2Etc29saWRhcmlhLWRiP2F1dGhTb3VyY2U9YWRtaW4=
  RabbitMq__Username: cmFiYml0bXF1c2Vy
  RabbitMq__Password: U0BAYmIxdE1RMTEyMw==
  ElasticSearch__ApiKey: ZHRwN3dwc0J0STRlQXlkWGVhRUs6MjhqNFpOUEdMZVdIeG1sMzRUUUhPUQ==

