apiVersion: batch/v1
kind: Job
metadata:
  name: kibana-setup
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: setup
          image: curlimages/curl
          command:
            - sh
            - -c
            - |
              until curl -s -u elastic:$(ELASTIC_PASSWORD) http://elasticsearch:9200; do sleep 5; done;
              curl -X POST -u elastic:$(ELASTIC_PASSWORD) \
              http://elasticsearch:9200/_security/user/kibana_system/_password \
              -H "Content-Type: application/json" \
              -d "{\"password\":\"$(KIBANA_PASSWORD)\"}"
          env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-secret
                  key: ELASTIC_PASSWORD
            - name: KIBANA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-secret
                  key: KIBANA_PASSWORD