apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazor-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blazor-frontend
  template:
    metadata:
      labels:
        app: blazor-frontend
    spec:
      containers:
        - name: blazor-frontend
          image: antniocarlod18/fiap-ong-esperanca-solidaria-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: frontend-config
            - secretRef:
                name: frontend-secrets
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
