apiVersion: v1
kind: Service
metadata:
  name: blazor-frontend
  namespace: default
  labels:
    app: blazor-frontend
spec:
  selector:
    app: blazor-frontend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
