apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: default
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  JwtSettings__Issuer: "https://backend-api/auth/login"
  JwtSettings__Audience: "https://backend-api/"
  MongoSettings__DatabaseName: "esperanca-solidaria-donations-db"
  MongoSettings__DonationsCollectionName: "donations"
  ElasticSearch__Uri: "http://elasticsearch:9200"
  ElasticSearch__IndexName: "esperanca-solidaria-worker"
  ElasticApm__ServerUrl: "http://apm-server:8200"
  ElasticApm__ServiceName: "esperanca-solidaria-worker"
  ElasticApm__Environment: "Production"
  RabbitMq__Host: "rabbitmq"