apiVersion: v1
kind: Secret
metadata:
  name: worker-secrets
  namespace: default
type: Opaque
data:
  JwtSettings__Secret: N2NDUkd1T2djZ2VDVWdLM3lUZHhiZTRQSDdhbUZITUQ=  
  ElasticSearch__ApiKey: ZHRwN3dwc0J0STRlQXlkWGVhRUs6MjhqNFpOUEdMZVdIeG1sMzRUUUhPUQ==
  RabbitMQ__Username: cmFiYml0bXF1c2Vy
  RabbitMQ__Password: U0BAYmIxdE1RMTEyMw== 
  MongoSettings__ConnectionString: bW9uZ29kYjovL2FkbWluOlNDM2huJTQwMW1hbmdvJTIxQG1vbmdvZGIuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy9lc3BlcmFuY2Etc29saWRhcmlhLWRvbmF0aW9ucy1kYj9hdXRoU291cmNlPWFkbWlu
